"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Loader2, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { jobDetail } from "@/lib/api";
import { resolveDeck, uniqueTags, type ResolvedCard } from "@/lib/cards";
import { loadCustomCards } from "@/lib/custom-cards";
import { loadDeckMeta } from "@/lib/deck-store";
import { cn, difficultyTone } from "@/lib/utils";
import type { JobDetail } from "@/lib/types";

interface PrintShellProps {
  deckId: string;
}

export function PrintShell({ deckId }: PrintShellProps) {
  const [job, setJob] = useState<JobDetail | null>(null);
  const [layout, setLayout] = useState<"two-up" | "list" | "table">("two-up");
  const [hideAnswers, setHideAnswers] = useState(false);

  useEffect(() => {
    jobDetail(deckId).then(setJob).catch(() => setJob(null));
  }, [deckId]);

  const cards = useMemo<ResolvedCard[]>(() => {
    if (!job) return [];
    const custom = loadCustomCards(deckId);
    return resolveDeck(deckId, [...job.cards, ...custom]).filter((c) => !c.archived);
  }, [job, deckId]);

  const title = job ? loadDeckMeta(deckId).alias || job.filename : "";
  const tags = useMemo(() => uniqueTags(cards), [cards]);

  if (!job) {
    return (
      <div className="container flex min-h-[40vh] items-center justify-center">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
      <div className="border-b bg-background/95 backdrop-blur print:hidden">
        <div className="container flex flex-wrap items-center justify-between gap-3 py-4">
          <Link
            href={`/decks/${deckId}` as any}
            className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" /> Back to deck
          </Link>
          <div className="flex items-center gap-2">
            <div className="inline-flex rounded-md border bg-card p-0.5 text-xs">
              {(["two-up", "list", "table"] as const).map((l) => (
                <button
                  key={l}
                  onClick={() => setLayout(l)}
                  className={cn(
                    "rounded-sm px-2.5 py-1 capitalize",
                    layout === l ? "bg-secondary text-foreground" : "text-muted-foreground",
                  )}
                >
                  {l}
                </button>
              ))}
            </div>
            <label className="flex cursor-pointer items-center gap-1.5 text-xs">
              <input
                type="checkbox"
                checked={hideAnswers}
                onChange={(e) => setHideAnswers(e.target.checked)}
              />
              Hide answers
            </label>
            <Button onClick={() => window.print()}>
              <Printer className="h-4 w-4" /> Print
            </Button>
          </div>
        </div>
      </div>

      <div className="container py-8 print:py-0">
        <div className="mx-auto max-w-4xl bg-white p-8 text-slate-900 shadow-sm print:shadow-none print:p-0">
          <header className="border-b pb-4">
            <p className="text-xs uppercase tracking-wide text-slate-500">Study sheet</p>
            <h1 className="font-display text-3xl font-bold">{title}</h1>
            <p className="mt-1 text-sm text-slate-600">
              {cards.length} cards - generated by mneme via {job.config.model}
            </p>
            {tags.length > 0 && (
              <p className="mt-2 flex flex-wrap gap-1 text-[10px] uppercase tracking-wide text-slate-500">
                {tags.map((t) => (
                  <span key={t} className="rounded-full border px-2 py-0.5">
                    #{t}
                  </span>
                ))}
              </p>
            )}
          </header>

          {layout === "two-up" && (
            <div className="grid gap-3 pt-5 sm:grid-cols-2">
              {cards.map((c, i) => (
                <PrintCard key={c.id} card={c} index={i + 1} hideAnswers={hideAnswers} />
              ))}
            </div>
          )}

          {layout === "list" && (
            <div className="divide-y pt-5">
              {cards.map((c, i) => (
                <div key={c.id} className="py-3">
                  <div className="flex items-baseline gap-2">
                    <span className="font-mono text-xs text-slate-400">{i + 1}.</span>
                    <p className="font-semibold">{c.question}</p>
                  </div>
                  {!hideAnswers && (
                    <p className="ml-6 mt-1 text-sm text-slate-700">{c.answer}</p>
                  )}
                </div>
              ))}
            </div>
          )}

          {layout === "table" && (
            <table className="mt-5 w-full text-sm">
              <thead className="text-left text-xs uppercase text-slate-500">
                <tr>
                  <th className="w-8 pb-2">#</th>
                  <th className="pb-2">Question</th>
                  {!hideAnswers && <th className="w-1/3 pb-2">Answer</th>}
                </tr>
              </thead>
              <tbody className="divide-y">
                {cards.map((c, i) => (
                  <tr key={c.id} className="align-top">
                    <td className="py-2 font-mono text-xs text-slate-400">{i + 1}</td>
                    <td className="py-2">{c.question}</td>
                    {!hideAnswers && <td className="py-2 text-slate-700">{c.answer}</td>}
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>

      <style>{`
        @media print {
          body { background: white !important; }
          .container { padding: 0 !important; }
          aside, header[role], nav, footer { display: none !important; }
        }
      `}</style>
    </>
  );
}

function PrintCard({ card, index, hideAnswers }: { card: ResolvedCard; index: number; hideAnswers: boolean }) {
  const tone = difficultyTone(card.effective_difficulty);
  return (
    <div className="break-inside-avoid rounded-md border border-slate-200 p-3">
      <div className="flex items-center justify-between text-[10px] uppercase tracking-wide text-slate-500">
        <span>Card {index}</span>
        <Badge variant="outline" className={cn(tone.bg, tone.fg, "border-0 text-[10px]")}>
          {tone.label}
        </Badge>
      </div>
      <p className="mt-1.5 font-semibold leading-snug">{card.question}</p>
      <div className="my-2 h-px bg-slate-200" />
      {hideAnswers ? (
        <div className="h-12 rounded border border-dashed border-slate-200" />
      ) : (
        <p className="text-sm text-slate-700">{card.answer}</p>
      )}
    </div>
  );
}
